image: basaltinc/docker-node-php-base

options:
  size: 2x  # all steps in this repo get 8GB memory
  docker: true

pipelines:
  default:
    - step:
        name: Install, Build, Test, Deploy
        script:
          - npm i -g --unsafe-perm now@latest
          - yarn deploy:test

  branches:
      epic/v2:
        - step:
            name: Install, Build, Test, Deploy
            script:
              - npm i -g --unsafe-perm now@latest
              - yarn deploy:prod

#definitions:
#  caches:
#    yarn: $HOME/.yarn-cache
