image: basaltinc/docker-node-php-base

pipelines:
  branches:
    master:
      - step:
          caches:
            - composer
            - node
            - pip
            - yarn
          script:
            - curl -o- -L https://yarnpkg.com/install.sh | bash -s
            - export PATH=$HOME/.yarn/bin:$PATH
            - yarn --version && npm --version && node --version && composer --version && php --version
            - apt-get update && apt-get install -y python-dev
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python get-pip.py
            - pip install awscli
            - yarn install --unsafe-perm --cache-folder=$HOME/.yarn-cache
            - npm test
            - npm run compile
            - aws s3 sync ./ s3://design.basalt.io --exclude "node_modules/*" --exclude ".git/*" --exclude "pattern-lab/vendor/*" --delete
    epic/v2:
      - step:
          caches:
            - composer
            - node
            - yarn
          script:
            - yarn --version && npm --version && node --version && composer --version && php --version
            - yarn install --unsafe-perm --cache-folder=$HOME/.yarn-cache
            - yarn test
            - yarn run deploy:prod
  default:
    - step:
        caches:
        - composer
        - node
        - yarn
        script:
        - yarn --version && npm --version && node --version && composer --version && php --version
        - yarn install --unsafe-perm --cache-folder=$HOME/.yarn-cache
        - yarn test
        - yarn run deploy

definitions:
  caches:
    yarn: $HOME/.yarn-cache
