# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  prep:
    working_directory: ~/repo
    docker:
      - image: basaltinc/docker-node-php-base
    steps:
      - run: checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --no-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: basaltinc/docker-node-php-base
    steps:
      - run: yarn test

  build:
    docker:
      - image: basaltinc/docker-node-php-base
    steps:
      - run: yarn build

  full_test:
    docker:
      - image: basaltinc/docker-node-php-base
    steps:
      - run: ./scripts/e2e-simple.sh

  release:
    docker:
      - image: basaltinc/docker-node-php-base
    steps:
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              #git config --global push.default upstream
              ./scripts/release.sh
              ./scripts/create-bedrock-deploy/deploy.sh
              #git checkout develop
              #git pull
              #git merge master
              #git push
            fi

  deploy:
    docker:
      - image: basaltinc/docker-node-php-base
    steps:
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              #git config --global push.default upstream
              ./scripts/release.sh
              ./scripts/create-bedrock-deploy/deploy.sh
              #git checkout develop
              #git pull
              #git merge master
              #git push
            fi

workflows:
  version: 2
  all_the_things:
    jobs:
      - prep
      - test:
          requires:
            - prep
      - build:
          requires:
            - prep
      - full_test:
          requires:
            - prep

