# Docs https://circleci.com/docs/2.0
version: 2.1

orbs:
  cypress: cypress-io/cypress@1 # https://circleci.com/orbs/registry/orb/cypress-io/cypress

# CircleCI maintains a library of pre-built images: https://circleci.com/docs/2.0/circleci-images/
executors:
  base:
    docker:
      - image: basaltinc/docker-node-php-base:latest
    working_directory: ~/repo
  cypress-with-php:  # This is an extension of the Basaltinc Node + Php image used for Knapsack that includes global cypress dependencies
    docker:
      - image: basaltinc/docker-node-php-cypress:latest # https://cloud.docker.com/u/basaltinc/repository/docker/basaltinc/docker-node-php-cypress/general
    working_directory: ~/repo
  base-w-browsers:
    docker:
      - image: basaltinc/docker-node-php-browsers:latest
    working_directory: ~/repo


# types: string, boolean, integer, enum, executor, steps, environment variable name ~ https://circleci.com/docs/2.0/reusing-config/#parameter-types
commands:
  deploy-to-now:
    description: Deploy to now.sh
    steps:
      - run: mkdir ~/artifacts || true
      - run: npm i --unsafe-perm -g now
      - run:
          command: now deploy --scope basalt --token $ZEIT_TOKEN && sleep 3
          no_output_timeout: 20m
      # @todo ensure this script grabs correct url from previous step
      - run: ./scripts/create-github-deploy.js
      - run: cat ~/artifacts/now-url.txt
      - persist_to_workspace:
          root: '~'
          paths:
            - artifacts/now-url.txt

jobs:
  setup:
    executor: base
    steps:
      - checkout
      - run: mkdir ~/artifacts ~/.yarn-cache
      - restore_cache:
          keys:
            - global
            - v1-deps-{{ checksum "yarn.lock" }}
      - run: yarn cache dir # just want to see what directory it is in, might be in ~/.cache/yarn
      - run: yarn install --frozen-lockfile --cache-folder ~/.yarn-cache
      - save_cache:
          key: global
          paths:
            - ~/.cache
            - ~/.npm
            - ~/.yarn-cache
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules
      - run: yarn build
      - persist_to_workspace:
          root: '~'
          paths:
            - repo
            - artifacts
            - .ssh
            - .cache/Cypress

  test--cypress:
    executor: cypress-with-php
    steps:
      - attach_workspace:
          at: '~'
      - run: ./node_modules/.bin/cypress verify
      - run: yarn test:cypress

  test--basics:
    executor: base
    steps:
      - attach_workspace:
          at: '~'
      - run: yarn lint:js
      - run: yarn lint:style
      - run: yarn test:knapsack
      - run: yarn jest
      - run: yarn build:private
      - run: yarn test:examples

  test--publish:
    executor: base
    steps:
      - attach_workspace:
          at: '~'
      - run: ./scripts/test-publish.sh

  docs:
    executor: base
    steps:
      - attach_workspace:
          at: '~'
      - run: yarn build:docs

workflows:
  version: 2
  main:
    jobs:
      - setup
      - test--basics:
          requires:
            - setup
      - test--cypress:
          requires:
            - setup
      - test--publish:
          requires:
            - setup
      - docs:
          requires:
            - setup
#      - deploy--stage:
#          requires:
#            - setup
#            - test--jest
#            - test--cypress
#          context: main tokens
#      - release:
#          requires:
#            - setup
#            - test--knapsack
#            - test--jest
#            - test--cypress
#          context: main tokens
