v: 2.6.0
overrideConfig: false
ie:
  - DS_Store
  - less
  - scss
id:
  - scss
  - .svn
  - .sass-cache
cleanPublic: 'true'
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: ../build/pattern-lab
sourceDir: source
defaultPattern: all
defaultShowPatternInfo: false
lineageMatch: >-
  {%([ ]+)?(?:include|extends|embed)(
  |\()[&quot;\&#039;]([\/.@A-Za-z0-9-_]+)[&quot;\&#039;]([\s\S+]*?)%}
lineageMatchKey: 3
patternExtension: twig
twigDebug: false
twigAutoescape: html
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
  - hay
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
plugins:
  faker:
    enabled: true
    locale: en_US
  twigNamespaces:
    enabled: true
    namespaces:
      svgs:
        paths:
          - ../images/svgs
      utils:
        paths:
          - source/_utils
      styleguide:
        paths:
          - source/_patterns/00-styleguide
          - source/_patterns/00-styleguide/00-breakpoints
          - source/_patterns/00-styleguide/01-branding
          - source/_patterns/00-styleguide/05-colors
          - source/_patterns/00-styleguide/10-spacing
          - source/_patterns/00-styleguide/15-typography
          - source/_patterns/00-styleguide/animations/01-transitions
          - source/_patterns/00-styleguide/forms
          - source/_patterns/00-styleguide/icons
          - source/_patterns/00-styleguide/utilities
          - source/_patterns/00-styleguide/utilities/borders
      layouts:
        paths:
          - source/_patterns/02-layouts
          - source/_patterns/02-layouts/grids
          - source/_patterns/02-layouts/site
      components:
        paths:
          - source/_patterns/03-components
          - source/_patterns/03-components/avatar
          - source/_patterns/03-components/basic-block
          - source/_patterns/03-components/blog-teaser
          - source/_patterns/03-components/button
          - source/_patterns/03-components/cta
          - source/_patterns/03-components/exec-bio
          - source/_patterns/03-components/forms
          - source/_patterns/03-components/hero
          - source/_patterns/03-components/list
          - source/_patterns/03-components/logo
          - source/_patterns/03-components/media-block
          - source/_patterns/03-components/media-tile
          - source/_patterns/03-components/site-footer
          - source/_patterns/03-components/site-header
          - source/_patterns/03-components/social
      templates:
        paths:
          - source/_patterns/04-templates
          - source/_patterns/04-templates/blog-list
          - source/_patterns/04-templates/blog-post
