# https://www.netlifycms.org/docs/intro
backend:
  name: github
  repo: basaltinc/knapsack
  branch: master
  commit_messages:
    create: 'docs: create {{collection}} “{{slug}}” [skip ci]'
    update: 'docs: update {{collection}} “{{slug}}” [skip ci]'
    delete: 'docs: delete {{collection}} “{{slug}}” [skip ci]'
    uploadMedia: 'docs: upload “{{path}}” [skip ci]'
    deleteMedia: 'docs: delete “{{path}}” [skip ci]'

publish_mode: editorial_workflow
squash_merges: true

media_folder: "docs-site/static/img"
public_folder: "/img"

collections:
  - name: "docs" # Used in routes, e.g., /admin/collections/docs
    label: "Docs" # Used in the UI
    folder: "docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
