name: Main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn install --frozen-lockfile
        #if:
        #name:
      - run: yarn build
      - run: yarn lint:style
      - run: yarn lint:js
      - run: yarn test:knapsack
      - run: yarn jest
      - run: yarn build:private
      - run: yarn build:docs
      - run: yarn test:examples
#      - run: yarn test:cypress
